### ISSUE TITLE
bug: wrong nasted glue evaluation

### ISSUE THREAD

**Issue by Eomm** [nearform/sql#104]
When multiple glue commands are executed, the SQL output is not a valid SQL statement

In this case, I have:

- input array `data` to be glued togheter
- a parent `values` array that glue every data item
- the final SQL statement

```js
const SQL = require('@nearform/sql')

const data = ['a', 'b'].map((letter) => SQL`${letter}`)

const values = [
  SQL`(${SQL.glue(data, ', ')})`, //
  SQL`(${SQL.glue(data, ', ')})`, //
]

const insertMultiple = SQL`INSERT INTO "foo" (foo, baz) VALUES ${SQL.glue(values, ' , ')}`
console.log(insertMultiple.debug)
// INSERT INTO "foo" (foo, baz) VALUES ('a', 'b')'a', 'b'(undefined)
```

**Comment by andrewwood2** [comment]
This is working fine for me. Can you double check you're seeing an issue and if so send me a message to help me recreate it.

`test('should be able to use nested glue evaluations', t => {
  const data = ['a', 'b'].map(letter => SQL`${letter}`)

  const values = [
    SQL`(${SQL.glue(data, ', ')})`,
    SQL`(${SQL.glue(data, ', ')})`
  ]

  const sql = SQL`INSERT INTO "foo" (foo, baz) VALUES ${SQL.glue(
    values,
    ' , '
  )}`
  t.equal(
    sql.text,
    `INSERT INTO "foo" (foo, baz) VALUES ($1, $2) , ($3, $4)`
  )
  t.same(
    sql.values,
    ["a","b","a","b"]
  )
  t.equal(
    sql.debug,
    `INSERT INTO "foo" (foo, baz) VALUES ('a', 'b') , ('a', 'b')`
  )
  t.end()
})`
