### ISSUE TITLE
Glue is not working when used for `IN` clauses

### ISSUE THREAD

**Issue by p16** [nearform/sql#13]
I think I've found a bug in how `glue` handles a list of only parameters (like in a `WHERE x IN (...)` clause.

Doing something like 

```javascript
const sql = SQL`
  SELECT
    *
  FROM
    test
  WHERE
    test.id IN (
`
const sqlIds = listOfIds.map(id => SQL`${id}`)
sql.append(sql.glue(sqlIds, ' , '))
sql.append(SQL`
  )
`)
```

will not produce a list of ids in the `IN` clause because of the [filter here](https://github.com/nearform/sql/blob/master/SQL.js#L11).

In this scenario the `sqlIds` array of `SqlStatement` will be something like the following

```
[ 
  SqlStatement {
    strings: [ '', '' ],
    values: [ 'bde1bf79-ac0d-4dfc-aae2-a74cf18da945' ] 
  },
  SqlStatement {
    strings: [ '', '' ],
    values: [ 'a562808a-f4f8-4598-aee4-7af560759b18' ] 
  },
  ...
]
```

and the filter (linked above) will consider all those statement as empty.

**Comment by mcollina** [comment]
A PR would be highly welcomed :D.
