### ISSUE TITLE
OS Command injections

### ISSUE THREAD

**Issue by Avivbens** [nearform/sql#204]
Hi 👋

Really liked this tool! Super convenient. 

Any chance you're also supporting OS Command protection?
Could be just the same logic, if I think about that...

**Comment by simoneb** [comment]
Can you provide an example of something like that?

**Comment by Avivbens** [comment]
> Can you provide an example of something like that?

Sure!

Assume I'd like to execute that:

```typescript
// I'd like to apply some protection to these dynamic values, as the user can affect them
const command = `mdfind ${kind} -name "${name}" ${onlyInStr ?? ''}`
const { stdout } = await execPromise(query, { maxBuffer: 10_000_000 })
```


You can see a reference [in here](https://github.com/Avivbens/alfred-advance-fs-search/blob/master/src/services/search.service.ts#L42-L44)

**Comment by antongolub** [comment]
zurk just builds a flexible abstraction on top of the process spawner.
zx has a broader scope. It is a toolchain that comprehensively improves devx in the tasks of writing scripts for various purposes.
