### ISSUE TITLE
VSCode syntax highlighting or recommend existing extension

### ISSUE THREAD

**Issue by penx** [nearform/sql#36]
It would be great to have SQL syntax highlighting in VSCode, perhaps an existing extension already does this and could be added to the readme? Or else produce a VSCode extension specifically for this library?

**Comment by capaj** [comment]
This vscode extension seems to work fine with this librrary: https://marketplace.visualstudio.com/items?itemName=thebearingedge.vscode-sql-lit

before:
![image](https://user-images.githubusercontent.com/1305378/129065676-fdcc153a-0073-42a0-b19c-90f12d6dce3e.png)

after:
![image](https://user-images.githubusercontent.com/1305378/129065632-0f7e9ecc-e617-422b-8d56-970f511d9dfd.png)

I'll try to add a PR for the readme
