### ISSUE TITLE
Easy way to remove string literal?

### ISSUE THREAD

**Issue by Donny-H** [nearform/sql#38]
Love the product, very useful. One issue I have run into: some queries can't be used with quoted string literals, for example:

`const tCode = L5Kfad`
```let sessionQuery = SQL`ALTER TABLE sessions ADD COLUMN prod_${tCode} VARCHAR```

Produces the query:

`ALTER TABLE sessions ADD COLUMN prod_'L5Kfad' VARCHAR`

But this particular query will not work with the column name in quotes. Is there an easy way to remove quotes from the inserted variable?

Direct concat works fine:

`let sessionQuery = "ALTER TABLE sessions ADD COLUMN prod_" + tCode + " VARCHAR";`

I hope I haven't missed something. Thanks

**Comment by ikhsanalatsary** [comment]
@Donny-H recently I faced this issue too. so, I did a little hack, directly mutate the `strings `property. for your case. is something like this:
```javascript
let tCode = 'L5Kfad'
let sessionQuery = SQL`ALTER TABLE sessions ADD COLUMN `
let strings = Array.from(sessionQuery.strings)
strings[strings.length -1] += `prod_${tCode} `
sessionQuery.strings = strings
sessionQuery.append(SQL`VARCHAR `)
console.log(sessionQuery.sql)
```

and this is the playground to see https://replit.com/@ikhsanalatsary/nearformSQL-playground
PS: don't forget the additional space

**Comment by simoneb** [comment]
You can use the `unsafe` option

```js
const tCode = 'L5Kfad'
const sessionQuery = SQL`ALTER TABLE sessions ADD COLUMN prod_`
sessionQuery.append(SQL`${tCode} VARCHAR`, { unsafe: true })
```

**Comment by ikhsanalatsary** [comment]
> You can use the `unsafe` option
> 
> ```js
> const tCode = 'L5Kfad'
> const sessionQuery = SQL`ALTER TABLE sessions ADD COLUMN prod_`
> sessionQuery.append(SQL`${tCode} VARCHAR`, { unsafe: true })
> ```

nice. thank you
