### ISSUE TITLE
Using SQL.glue within template literal

### ISSUE THREAD

**Issue by penx** [nearform/sql#51]
In https://github.com/nearform/sql/issues/17 there was a request to use SQL.glue statically from within a template literal as follows:

```js
const query = SQL`INSERT INTO users (id) VALUES ${SQL.glue(idValues, ', ')}`
```

A PR (https://github.com/nearform/sql/pull/20) was raised that references this request, but the readme does not explicitly show this being used within a template literal.

I am trying to use it as follows:

```js
const idValues = ids.map(id => SQL`${id}`)
const sql = SQL`
  UPDATE my_table
  SET active = FALSE
  WHERE id IN (${SQL.glue(idValues, ',')})
`
```

This results in an 'invalid input syntax' error. I think this is because `sql.values` is `[SqlStatement]`, but should be the array of ids.

- Is it currently possible to use SQL.glue from within the template literal? (I haven't found a way yet)
- If so, can it be documented in the readme?
- If not, can support be added? This would be a nice to have, to help produce easier to read code and would hopefully work better with a [syntax highlighting](https://github.com/nearform/sql/issues/36) solution.

**Comment by mcollina** [comment]
This feature is not currently supported. Would you like to send a PR?

**Comment by paolochiodi** [comment]
This may use a mechanism similar to the one we put in place for [quoteIdent](https://github.com/nearform/sql/pull/41).

I'd also argue that at this point we could move the entire interface to always use string interpolation and deprecate `append`.
This means that SQL should also tag the returned value so that 

```js
const a = SQL`FROM table`
const b = SQL`SELECT * ${a}`
```

would be equivalent to 

```js
const a = SQL`SELECT * ${a}`
a.append(SQL`FROM table`)
```

**Comment by paolochiodi** [comment]
@penx In your specific example you may not even need glue.

With Postgres you could write:

```js
const idValues = ids.map(id => SQL`${id}`)
const sql = SQL`
  UPDATE my_table
  SET active = FALSE
  WHERE id = ANY(${ids})
```

I'm not very familiar with mysql, but this should work:

```
const idValues = ids.map(id => SQL`${id}`)
const sql = SQL`
  UPDATE my_table
  SET active = FALSE
  WHERE id IN (${ids})
```

**Comment by simoneb** [comment]
I like the idea of deprecating the special methods in favor of the approach we used for the new unsafe and quoteIdent functions.

**Comment by penx** [comment]
WIP here, https://github.com/nearform/sql/pull/52

Extending .values looks like it will need some thinking, as we'd now have nested values.
